# Generated by Django 4.1.2 on 2022-11-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Mob', models.IntegerField(blank=True, null=True)),
                ('Email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('Password', models.CharField(blank=True, max_length=15, null=True)),
                ('Confirm', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
