# Generated by Django 4.1.2 on 2022-11-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Email_id',
            field=models.EmailField(blank=True, max_length=20, null=True),
        ),
    ]
