# Generated by Django 4.1.2 on 2022-11-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0003_products_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Name', models.CharField(blank=True, max_length=15, null=True)),
                ('Description', models.CharField(blank=True, max_length=30, null=True)),
                ('C_Image', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
