# Generated by Django 4.1.2 on 2022-11-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0004_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Admin',
        ),
    ]
