# Generated by Django 4.1.2 on 2023-01-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0006_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=25, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Sub', models.CharField(blank=True, max_length=50, null=True)),
                ('Msg', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
